version: '3.8'
services:
  db_website_builder:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: website_builder_saas
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: website_builder_saas
    ports: 
      - "5439:5432"
    volumes:
      - db_website_builder:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  db_website_builder: